# Generated by Django 5.2.6 on 2025-10-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ID платежа в Stripe",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_status",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Статус платежа в Stripe",
            ),
        ),
    ]
