version: '3.12'

services:
# ПРОПИСЫВАЕМ DJANGO приложение
  web:
    build: .
    command: sh -c "python manage.py collectstatic --noinput 
             && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    # тома для сохранения данных вне контейнера
    volumes:
      - .:/DJANGO_REST_HW
      - static_volume:/DJANGO_REST_HW/static
      - media_volume:/DJANGO_REST_HW/media
    ports:
      - "8000:8000"
    # условия запуска(не будет работать, пока не запустятся зависимости)
    depends_on:
      - db
      - redis
    #env_file не нужен, т.к. он есть в образе dockerfile и  используешь load_dotenv() в коде
      #и файл .env попал в контейнер (через COPY или volumes).
    environment:
      - USE_DOCKER=True #важный флаг переключения БД в settings

# ПРОПИСЫВАЕМ Celery
  worker:
    build: .
    command: celery -A config worker --loglevel=info --pool=eventlet
    depends_on:
      - redis
      - db
    volumes:
      - .:/DJANGO_REST_HW
    #env_file не нужен, так как файл .env лежит рядом с docker-compose.yml
    #volumes: .:/DJANGO_REST_HW → значит, .env доступен → load_dotenv() прочитает его → переменные будут в os.getenv()
    # environment не нужен, так как я ничего не переопределяю и данные берутся из .env


# ПРОПИСЫВАЕМ Celery beat
  beat:
    build: .
    command: celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - db
    volumes:
      - .:/DJANGO_REST_HW
    #env_file не нужен, так как файл .env лежит рядом с docker-compose.yml

# ПРОПИСЫВАЕМ redis
  redis:
    # получаем образ с dockerhub
    image: redis:7-alpine
    ports:
      - "6379:6379"

#ПРОПИСЫВАЕМ ВЕБ СЕРВЕР
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"# если будете настраивать HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - web

# ПРОПИСЫВАЕМ postgres(db это DB_HOST)
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env #Хоть он лежит рядом, но лучше явно указать
      #Нужен так как мы переопределяем environment и берем
      # данные из .env который лежит рядом - РАБОТА НА УРОВНЕ КОНТЕЙНЕРА, А НЕ DJANGO

# Перечисляем имена томов без параметров, которые участвует в работе
volumes:
  postgres_data:
  static_volume:
  media_volume: