# Generated by Django 5.2.6 on 2025-10-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educations", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                help_text="URL видео на YouTube", verbose_name="Ссылка на видео"
            ),
        ),
    ]
