# Generated by Django 5.2.6 on 2025-10-06 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educations", "0003_alter_lesson_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=500.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Стоимость курса",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=100.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Стоимость урока",
            ),
        ),
    ]
